/* GENERATED by scripts/icons/build-registry.mts — do not edit by hand. */
import type { ComponentType, SVGProps } from "react"

import {
  Activity as LuActivity,
  ArrowDown as LuArrowDown,
  ArrowDownRight as LuArrowDownRight,
  ArrowRight as LuArrowRight,
  ArrowUpDown as LuArrowUpDown,
  ArrowUpRight as LuArrowUpRight,
  Bell as LuBell,
  Boxes as LuBoxes,
  CalendarDays as LuCalendarDays,
  Calendar as LuCalendar,
  Check as LuCheck,
  ChevronDown as LuChevronDown,
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronUp as LuChevronUp,
  CircleAlert as LuCircleAlert,
  CircleCheck as LuCircleCheck,
  Clock as LuClock,
  Copy as LuCopy,
  CornerDownLeft as LuCornerDownLeft,
  Download as LuDownload,
  EllipsisVertical as LuEllipsisVertical,
  Eye as LuEye,
  Filter as LuFilter,
  Fuel as LuFuel,
  Gauge as LuGauge,
  Inbox as LuInbox,
  Info as LuInfo,
  LayoutDashboard as LuLayoutDashboard,
  LayoutGrid as LuLayoutGrid,
  LifeBuoy as LuLifeBuoy,
  List as LuList,
  Loader2 as LuLoader2,
  LogOut as LuLogOut,
  Map as LuMap,
  MapPin as LuMapPin,
  Minus as LuMinus,
  MoreHorizontal as LuMoreHorizontal,
  OctagonX as LuOctagonX,
  PackageCheck as LuPackageCheck,
  PackagePlus as LuPackagePlus,
  Paintbrush as LuPaintbrush,
  PanelLeft as LuPanelLeft,
  Paperclip as LuPaperclip,
  Phone as LuPhone,
  Plus as LuPlus,
  RadioTower as LuRadioTower,
  RefreshCw as LuRefreshCw,
  RotateCcw as LuRotateCcw,
  Search as LuSearch,
  Settings as LuSettings,
  ShieldCheck as LuShieldCheck,
  Sparkles as LuSparkles,
  Trash as LuTrash,
  TriangleAlert as LuTriangleAlert,
  Truck as LuTruck,
  User as LuUser,
  Users as LuUsers,
  Wallet as LuWallet,
  X as LuX,
} from "lucide-react"
import {
  Pulse as PhPulse,
  ArrowDown as PhArrowDown,
  ArrowDownRight as PhArrowDownRight,
  ArrowRight as PhArrowRight,
  ArrowsDownUp as PhArrowsDownUp,
  ArrowUpRight as PhArrowUpRight,
  Bell as PhBell,
  Stack as PhStack,
  CalendarDots as PhCalendarDots,
  Calendar as PhCalendar,
  Check as PhCheck,
  CaretDown as PhCaretDown,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretUp as PhCaretUp,
  WarningCircle as PhWarningCircle,
  CheckCircle as PhCheckCircle,
  Clock as PhClock,
  Copy as PhCopy,
  ArrowElbowDownLeft as PhArrowElbowDownLeft,
  Download as PhDownload,
  DotsThreeVertical as PhDotsThreeVertical,
  Eye as PhEye,
  Funnel as PhFunnel,
  GasPump as PhGasPump,
  Gauge as PhGauge,
  Tray as PhTray,
  Info as PhInfo,
  SquaresFour as PhSquaresFour,
  GridFour as PhGridFour,
  Lifebuoy as PhLifebuoy,
  List as PhList,
  CircleNotch as PhCircleNotch,
  SignOut as PhSignOut,
  MapTrifold as PhMapTrifold,
  MapPin as PhMapPin,
  Minus as PhMinus,
  DotsThree as PhDotsThree,
  Prohibit as PhProhibit,
  Package as PhPackage,
  PaintBrush as PhPaintBrush,
  SidebarSimple as PhSidebarSimple,
  Paperclip as PhPaperclip,
  Phone as PhPhone,
  Plus as PhPlus,
  Broadcast as PhBroadcast,
  ArrowsClockwise as PhArrowsClockwise,
  ArrowCounterClockwise as PhArrowCounterClockwise,
  MagnifyingGlass as PhMagnifyingGlass,
  GearSix as PhGearSix,
  ShieldCheck as PhShieldCheck,
  Sparkle as PhSparkle,
  Trash as PhTrash,
  Warning as PhWarning,
  Truck as PhTruck,
  User as PhUser,
  Users as PhUsers,
  Wallet as PhWallet,
  X as PhX,
} from "@phosphor-icons/react"
import { SpeedFast as PxSpeedFast } from "pixelarticons/react/SpeedFast"
import { ArrowDown as PxArrowDown } from "pixelarticons/react/ArrowDown"
import { ArrowRight as PxArrowRight } from "pixelarticons/react/ArrowRight"
import { SortVertical as PxSortVertical } from "pixelarticons/react/SortVertical"
import { ArrowUp as PxArrowUp } from "pixelarticons/react/ArrowUp"
import { Bell as PxBell } from "pixelarticons/react/Bell"
import { Archive as PxArchive } from "pixelarticons/react/Archive"
import { Calendar as PxCalendar } from "pixelarticons/react/Calendar"
import { Check as PxCheck } from "pixelarticons/react/Check"
import { ChevronDown as PxChevronDown } from "pixelarticons/react/ChevronDown"
import { ChevronLeft as PxChevronLeft } from "pixelarticons/react/ChevronLeft"
import { ChevronRight as PxChevronRight } from "pixelarticons/react/ChevronRight"
import { ChevronUp as PxChevronUp } from "pixelarticons/react/ChevronUp"
import { SquareAlert as PxSquareAlert } from "pixelarticons/react/SquareAlert"
import { CheckDouble as PxCheckDouble } from "pixelarticons/react/CheckDouble"
import { Clock as PxClock } from "pixelarticons/react/Clock"
import { Copy as PxCopy } from "pixelarticons/react/Copy"
import { ArrowLeftBox as PxArrowLeftBox } from "pixelarticons/react/ArrowLeftBox"
import { Download as PxDownload } from "pixelarticons/react/Download"
import { MoreVertical as PxMoreVertical } from "pixelarticons/react/MoreVertical"
import { Eye as PxEye } from "pixelarticons/react/Eye"
import { Filter as PxFilter } from "pixelarticons/react/Filter"
import { BatteryMedium as PxBatteryMedium } from "pixelarticons/react/BatteryMedium"
import { SpeedMedium as PxSpeedMedium } from "pixelarticons/react/SpeedMedium"
import { Inbox as PxInbox } from "pixelarticons/react/Inbox"
import { CircleInfo as PxCircleInfo } from "pixelarticons/react/CircleInfo"
import { Layout as PxLayout } from "pixelarticons/react/Layout"
import { Grid2x22 as PxGrid2x22 } from "pixelarticons/react/Grid2x22"
import { Radio as PxRadio } from "pixelarticons/react/Radio"
import { Bulletlist as PxBulletlist } from "pixelarticons/react/Bulletlist"
import { Loader as PxLoader } from "pixelarticons/react/Loader"
import { Logout as PxLogout } from "pixelarticons/react/Logout"
import { Map as PxMap } from "pixelarticons/react/Map"
import { MapPin as PxMapPin } from "pixelarticons/react/MapPin"
import { Minus as PxMinus } from "pixelarticons/react/Minus"
import { MoreHorizontal as PxMoreHorizontal } from "pixelarticons/react/MoreHorizontal"
import { Close as PxClose } from "pixelarticons/react/Close"
import { Brush as PxBrush } from "pixelarticons/react/Brush"
import { Attachment as PxAttachment } from "pixelarticons/react/Attachment"
import { Phone as PxPhone } from "pixelarticons/react/Phone"
import { Plus as PxPlus } from "pixelarticons/react/Plus"
import { CellularSignal3 as PxCellularSignal3 } from "pixelarticons/react/CellularSignal3"
import { Reload as PxReload } from "pixelarticons/react/Reload"
import { Undo as PxUndo } from "pixelarticons/react/Undo"
import { Search as PxSearch } from "pixelarticons/react/Search"
import { Gear as PxGear } from "pixelarticons/react/Gear"
import { Shield as PxShield } from "pixelarticons/react/Shield"
import { Zap as PxZap } from "pixelarticons/react/Zap"
import { Trash as PxTrash } from "pixelarticons/react/Trash"
import { WarningDiamond as PxWarningDiamond } from "pixelarticons/react/WarningDiamond"
import { Truck as PxTruck } from "pixelarticons/react/Truck"
import { User as PxUser } from "pixelarticons/react/User"
import { Users as PxUsers } from "pixelarticons/react/Users"
import { Wallet as PxWallet } from "pixelarticons/react/Wallet"
import { X as PxX } from "pixelarticons/react/X"

export type Glyph = ComponentType<SVGProps<SVGSVGElement>>

/** One row per icon: the same idea, drawn by three different hands. */
export const registry = {
  Activity: { lucide: LuActivity as Glyph, phosphor: PhPulse as unknown as Glyph, pixel: PxSpeedFast as Glyph },
  ArrowDown: { lucide: LuArrowDown as Glyph, phosphor: PhArrowDown as unknown as Glyph, pixel: PxArrowDown as Glyph },
  ArrowDownRight: { lucide: LuArrowDownRight as Glyph, phosphor: PhArrowDownRight as unknown as Glyph, pixel: PxArrowDown as Glyph },
  ArrowRight: { lucide: LuArrowRight as Glyph, phosphor: PhArrowRight as unknown as Glyph, pixel: PxArrowRight as Glyph },
  ArrowUpDown: { lucide: LuArrowUpDown as Glyph, phosphor: PhArrowsDownUp as unknown as Glyph, pixel: PxSortVertical as Glyph },
  ArrowUpRight: { lucide: LuArrowUpRight as Glyph, phosphor: PhArrowUpRight as unknown as Glyph, pixel: PxArrowUp as Glyph },
  Bell: { lucide: LuBell as Glyph, phosphor: PhBell as unknown as Glyph, pixel: PxBell as Glyph },
  Boxes: { lucide: LuBoxes as Glyph, phosphor: PhStack as unknown as Glyph, pixel: PxArchive as Glyph },
  CalendarDays: { lucide: LuCalendarDays as Glyph, phosphor: PhCalendarDots as unknown as Glyph, pixel: PxCalendar as Glyph },
  Calendar: { lucide: LuCalendar as Glyph, phosphor: PhCalendar as unknown as Glyph, pixel: PxCalendar as Glyph },
  Check: { lucide: LuCheck as Glyph, phosphor: PhCheck as unknown as Glyph, pixel: PxCheck as Glyph },
  ChevronDown: { lucide: LuChevronDown as Glyph, phosphor: PhCaretDown as unknown as Glyph, pixel: PxChevronDown as Glyph },
  ChevronLeft: { lucide: LuChevronLeft as Glyph, phosphor: PhCaretLeft as unknown as Glyph, pixel: PxChevronLeft as Glyph },
  ChevronRight: { lucide: LuChevronRight as Glyph, phosphor: PhCaretRight as unknown as Glyph, pixel: PxChevronRight as Glyph },
  ChevronUp: { lucide: LuChevronUp as Glyph, phosphor: PhCaretUp as unknown as Glyph, pixel: PxChevronUp as Glyph },
  CircleAlert: { lucide: LuCircleAlert as Glyph, phosphor: PhWarningCircle as unknown as Glyph, pixel: PxSquareAlert as Glyph },
  CircleCheck: { lucide: LuCircleCheck as Glyph, phosphor: PhCheckCircle as unknown as Glyph, pixel: PxCheckDouble as Glyph },
  Clock: { lucide: LuClock as Glyph, phosphor: PhClock as unknown as Glyph, pixel: PxClock as Glyph },
  Copy: { lucide: LuCopy as Glyph, phosphor: PhCopy as unknown as Glyph, pixel: PxCopy as Glyph },
  CornerDownLeft: { lucide: LuCornerDownLeft as Glyph, phosphor: PhArrowElbowDownLeft as unknown as Glyph, pixel: PxArrowLeftBox as Glyph },
  Download: { lucide: LuDownload as Glyph, phosphor: PhDownload as unknown as Glyph, pixel: PxDownload as Glyph },
  EllipsisVertical: { lucide: LuEllipsisVertical as Glyph, phosphor: PhDotsThreeVertical as unknown as Glyph, pixel: PxMoreVertical as Glyph },
  Eye: { lucide: LuEye as Glyph, phosphor: PhEye as unknown as Glyph, pixel: PxEye as Glyph },
  Filter: { lucide: LuFilter as Glyph, phosphor: PhFunnel as unknown as Glyph, pixel: PxFilter as Glyph },
  Fuel: { lucide: LuFuel as Glyph, phosphor: PhGasPump as unknown as Glyph, pixel: PxBatteryMedium as Glyph },
  Gauge: { lucide: LuGauge as Glyph, phosphor: PhGauge as unknown as Glyph, pixel: PxSpeedMedium as Glyph },
  Inbox: { lucide: LuInbox as Glyph, phosphor: PhTray as unknown as Glyph, pixel: PxInbox as Glyph },
  Info: { lucide: LuInfo as Glyph, phosphor: PhInfo as unknown as Glyph, pixel: PxCircleInfo as Glyph },
  LayoutDashboard: { lucide: LuLayoutDashboard as Glyph, phosphor: PhSquaresFour as unknown as Glyph, pixel: PxLayout as Glyph },
  LayoutGrid: { lucide: LuLayoutGrid as Glyph, phosphor: PhGridFour as unknown as Glyph, pixel: PxGrid2x22 as Glyph },
  LifeBuoy: { lucide: LuLifeBuoy as Glyph, phosphor: PhLifebuoy as unknown as Glyph, pixel: PxRadio as Glyph },
  List: { lucide: LuList as Glyph, phosphor: PhList as unknown as Glyph, pixel: PxBulletlist as Glyph },
  Loader2: { lucide: LuLoader2 as Glyph, phosphor: PhCircleNotch as unknown as Glyph, pixel: PxLoader as Glyph },
  LogOut: { lucide: LuLogOut as Glyph, phosphor: PhSignOut as unknown as Glyph, pixel: PxLogout as Glyph },
  Map: { lucide: LuMap as Glyph, phosphor: PhMapTrifold as unknown as Glyph, pixel: PxMap as Glyph },
  MapPin: { lucide: LuMapPin as Glyph, phosphor: PhMapPin as unknown as Glyph, pixel: PxMapPin as Glyph },
  Minus: { lucide: LuMinus as Glyph, phosphor: PhMinus as unknown as Glyph, pixel: PxMinus as Glyph },
  MoreHorizontal: { lucide: LuMoreHorizontal as Glyph, phosphor: PhDotsThree as unknown as Glyph, pixel: PxMoreHorizontal as Glyph },
  OctagonX: { lucide: LuOctagonX as Glyph, phosphor: PhProhibit as unknown as Glyph, pixel: PxClose as Glyph },
  PackageCheck: { lucide: LuPackageCheck as Glyph, phosphor: PhPackage as unknown as Glyph, pixel: PxArchive as Glyph },
  PackagePlus: { lucide: LuPackagePlus as Glyph, phosphor: PhPackage as unknown as Glyph, pixel: PxArchive as Glyph },
  Paintbrush: { lucide: LuPaintbrush as Glyph, phosphor: PhPaintBrush as unknown as Glyph, pixel: PxBrush as Glyph },
  PanelLeft: { lucide: LuPanelLeft as Glyph, phosphor: PhSidebarSimple as unknown as Glyph, pixel: PxLayout as Glyph },
  Paperclip: { lucide: LuPaperclip as Glyph, phosphor: PhPaperclip as unknown as Glyph, pixel: PxAttachment as Glyph },
  Phone: { lucide: LuPhone as Glyph, phosphor: PhPhone as unknown as Glyph, pixel: PxPhone as Glyph },
  Plus: { lucide: LuPlus as Glyph, phosphor: PhPlus as unknown as Glyph, pixel: PxPlus as Glyph },
  RadioTower: { lucide: LuRadioTower as Glyph, phosphor: PhBroadcast as unknown as Glyph, pixel: PxCellularSignal3 as Glyph },
  RefreshCw: { lucide: LuRefreshCw as Glyph, phosphor: PhArrowsClockwise as unknown as Glyph, pixel: PxReload as Glyph },
  RotateCcw: { lucide: LuRotateCcw as Glyph, phosphor: PhArrowCounterClockwise as unknown as Glyph, pixel: PxUndo as Glyph },
  Search: { lucide: LuSearch as Glyph, phosphor: PhMagnifyingGlass as unknown as Glyph, pixel: PxSearch as Glyph },
  Settings: { lucide: LuSettings as Glyph, phosphor: PhGearSix as unknown as Glyph, pixel: PxGear as Glyph },
  ShieldCheck: { lucide: LuShieldCheck as Glyph, phosphor: PhShieldCheck as unknown as Glyph, pixel: PxShield as Glyph },
  Sparkles: { lucide: LuSparkles as Glyph, phosphor: PhSparkle as unknown as Glyph, pixel: PxZap as Glyph },
  Trash: { lucide: LuTrash as Glyph, phosphor: PhTrash as unknown as Glyph, pixel: PxTrash as Glyph },
  TriangleAlert: { lucide: LuTriangleAlert as Glyph, phosphor: PhWarning as unknown as Glyph, pixel: PxWarningDiamond as Glyph },
  Truck: { lucide: LuTruck as Glyph, phosphor: PhTruck as unknown as Glyph, pixel: PxTruck as Glyph },
  User: { lucide: LuUser as Glyph, phosphor: PhUser as unknown as Glyph, pixel: PxUser as Glyph },
  Users: { lucide: LuUsers as Glyph, phosphor: PhUsers as unknown as Glyph, pixel: PxUsers as Glyph },
  Wallet: { lucide: LuWallet as Glyph, phosphor: PhWallet as unknown as Glyph, pixel: PxWallet as Glyph },
  X: { lucide: LuX as Glyph, phosphor: PhX as unknown as Glyph, pixel: PxX as Glyph },
} satisfies Record<string, { lucide: Glyph; phosphor?: Glyph; pixel?: Glyph }>

export const iconNames = Object.keys(registry) as (keyof typeof registry)[]
